### PR TITLE
Add custom JavaScript for back button with smooth scroll

### PR DESCRIPTION
**Pull request by pmelchor**
I have added the custom JavaScript @rmzelle suggested in issue https://github.com/citation-style-language/citation-style-language.github.io/issues/4 to make the back button work with in-page links.

_Note to self and anybody else familiar with npm scripts:_
We now have a _csl.js file and an updated package.json: the uglify npm script now includes _csl.js in main.min.js when the scripts are rebuilt (this requires having npm locally, and running both `npm install` and `npm run build:js`)

### CODE REVIEW

**Comment by rmzelle** [comment]
When I hover over a TOC entry at e.g. http://localhost:4000/developers/, the target is http://localhost:4000/developers/#mappings. But clicking the entry sends me to http://localhost:4000/developers/#/mappings (note the extra slash). Is that intentional?

**Comment by pmelchor** [comment]
It has to do with the smooth-scrolling plugin (which is the original cause of the in-page links not showing in the address bar). The plugin can be "hacked" as we did here but at the cost of that slight oddity.

We can either keep the  /#/ type urls for the internal links or remove the smooth-scrolling plugin.

**Comment by rmzelle** [comment]
@adam3smith, thoughts? See the two comments above. Looks like we can choose between more standard page anchors (`developers/#mappings`) without smooth scrolling or faked anchors (`developers/#mappings`) with smooth scrolling.

The website currently has smooth scrolling without any page anchors (see e.g. http://citationstyles.org/developers/).

**Comment by adam3smith** [comment]
I don't see the harm in the faked anchors and I like the smooth scrolling a lot. (Saying this without having tested the proposed version, but I think the description is pretty clear).

**Comment by rmzelle** [comment]
Okay, thanks @pmelchor!

**Pull request merged**
